<?php
 $title = 'Login - InputFilter';

 $this->headTitle($title);
 $form  = $this->form;
 $form->setName('login');
 $form->setAttributes([
    'class'=>'form-horizontal',
    'id'=>'login-form',
    'action'=>'#',
 ]);
 $form->prepare();
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h2><?=$this->escapeHtml($title)?></h2>
    </div>
    <div class="col-md-4 col-md-offset-4">
    <?=$this->form()->openTag($form);?>
        <div class="form-group">
            <?=$this->formLabel($form->get('email'))?>
            <div class="col-md-9">
                <?=$this->formElement($form->get('email'))?>
            </div>
        </div>
        <div class="form-group">
            <?=$this->formLabel($form->get('password'))?>
            <div class="col-md-9">
                <?=$this->formElement($form->get('password'))?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6 col-md-offset-3">
                <?=$this->formLabel($form->get('rememberme'))?>
                <?=$this->formElement($form->get('rememberme'))?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3 col-md-offset-9">
                <?=$this->formRow($form->get('submitbutton'))?>
            </div>
        </div>

    <?=$this->form()->closeTag($form)?> <!--close form-->
    </div>
</div>
