<?php
$title = 'Upload Multi-File';
$this->headTitle($title);

$form  = $this->form;
$form->setName('upload-multi-file');
$form->setAttributes([
    'enctype'=>'multipart/form-data',
    'action'=> $this->url('file-upload',[
        'controller'=>'UploadFileController',
        'action'=>'uploadMultipleFiles',
    ]),
    'method'=>"POST",

]);

$form->prepare();
?>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <?=$this->form()->openTag($form);?>
        <?=$this->formRow($form->get('file-upload'))?>
        <?=$this->formRow($form->get('btnSubmit'))?>


        <?=$this->form()->closeTag($form)?> <!--close form-->
    </div>
</div>



